// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCeIUFyiDoTYou9G6fr3BeJlBj_YINM7HQ',
    appId: '1:329229890711:web:bb302f255c3f700a7d25d2',
    messagingSenderId: '329229890711',
    projectId: 'fire-2cc68',
    authDomain: 'fire-2cc68.firebaseapp.com',
    storageBucket: 'fire-2cc68.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDT_OqLuXUdsek-FkfJnZSqf5xgUymr44E',
    appId: '1:329229890711:android:70f5ee4e1d4e79887d25d2',
    messagingSenderId: '329229890711',
    projectId: 'fire-2cc68',
    storageBucket: 'fire-2cc68.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDvCtc8vwctfUwc0_yAkQoI7KpNEQ-tDEI',
    appId: '1:329229890711:ios:aec419efdd88adf67d25d2',
    messagingSenderId: '329229890711',
    projectId: 'fire-2cc68',
    storageBucket: 'fire-2cc68.appspot.com',
    iosClientId: '329229890711-d698ss6u8n196naqi7o4ne7v8avpoqgv.apps.googleusercontent.com',
    iosBundleId: 'com.example.myapp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDvCtc8vwctfUwc0_yAkQoI7KpNEQ-tDEI',
    appId: '1:329229890711:ios:aec419efdd88adf67d25d2',
    messagingSenderId: '329229890711',
    projectId: 'fire-2cc68',
    storageBucket: 'fire-2cc68.appspot.com',
    iosClientId: '329229890711-d698ss6u8n196naqi7o4ne7v8avpoqgv.apps.googleusercontent.com',
    iosBundleId: 'com.example.myapp',
  );
}
